<?php

use Carbon\Carbon;

return [
    [
        'title' => 'Panduan Lengkap Pemrograman dengan CodeIgniter',
        'description' => 'Pelajari bagaimana membangun aplikasi web yang kuat dengan menggunakan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
            ['name' => 'php', 'url' => '/tags/php/'],
        ],
    ],
    [
        'title' => 'Memahami Konsep MVC dalam Laravel',
        'description' => 'Pelajari konsep Model-View-Controller (MVC) dalam pembangunan aplikasi dengan Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'mvc', 'url' => '/tags/mvc/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Pemrograman Web dengan Laravel',
        'description' => 'Pelajari cara membangun aplikasi web modern menggunakan Laravel framework.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
            ['name' => 'php', 'url' => '/tags/php/'],
        ],
    ],
    [
        'title' => 'Membangun RESTful API dengan Laravel',
        'description' => 'Pelajari cara merancang dan mengembangkan RESTful API yang kuat menggunakan Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'restful api', 'url' => '/tags/restful-api/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Pengenalan CRUD dengan CodeIgniter',
        'description' => 'Pelajari dasar-dasar operasi CRUD (Create, Read, Update, Delete) menggunakan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'crud', 'url' => '/tags/crud/'],
            ['name' => 'database', 'url' => '/tags/database/'],
        ],
    ],
    [
        'title' => 'Mengoptimalkan Performa Laravel',
        'description' => 'Pelajari teknik-teknik optimasi untuk meningkatkan performa aplikasi web dengan Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'performance', 'url' => '/tags/performance/'],
            ['name' => 'optimization', 'url' => '/tags/optimization/'],
        ],
    ],
    [
        'title' => 'Panduan Lengkap Pemrograman dengan CodeIgniter',
        'description' => 'Pelajari bagaimana membangun aplikasi web yang kuat dengan menggunakan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
            ['name' => 'php', 'url' => '/tags/php/'],
        ],
    ],
    [
        'title' => 'Membangun Aplikasi Modern dengan Laravel',
        'description' => 'Pelajari cara membangun aplikasi web modern dan efisien menggunakan framework Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
            ['name' => 'php', 'url' => '/tags/php/'],
        ],
    ],
    [
        'title' => 'Memahami Konsep MVC dalam CodeIgniter',
        'description' => 'Pelajari konsep Model-View-Controller (MVC) dalam pengembangan aplikasi dengan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'mvc', 'url' => '/tags/mvc/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Membangun Aplikasi E-Commerce dengan Laravel',
        'description' => 'Pelajari cara membuat aplikasi e-commerce modern menggunakan framework Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'e-commerce', 'url' => '/tags/e-commerce/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Optimasi Kinerja Aplikasi dengan CodeIgniter',
        'description' => 'Pelajari teknik-teknik optimasi untuk meningkatkan kinerja aplikasi web menggunakan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'performance', 'url' => '/tags/performance/'],
            ['name' => 'optimization', 'url' => '/tags/optimization/'],
        ],
    ],
    [
        'title' => 'Membangun Aplikasi Real-Time dengan Laravel',
        'description' => 'Pelajari cara membuat aplikasi web real-time interaktif menggunakan framework Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'real-time', 'url' => '/tags/real-time/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'CodeIgniter: Membangun Aplikasi E-Commerce',
        'description' => 'Pelajari cara membangun platform e-commerce yang canggih menggunakan framework CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'e-commerce', 'url' => '/tags/e-commerce/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Laravel: Aplikasi Mobile dengan Laravel API',
        'description' => 'Pelajari cara membuat aplikasi mobile interaktif menggunakan Laravel sebagai backend API.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'mobile app', 'url' => '/tags/mobile-app/'],
            ['name' => 'api development', 'url' => '/tags/api-development/'],
        ],
    ],
    [
        'title' => 'Laravel: Membangun Aplikasi Blog Modern',
        'description' => 'Pelajari cara membangun aplikasi blog modern dan responsif menggunakan framework Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'blog', 'url' => '/tags/blog/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'CodeIgniter: Membangun Aplikasi Hotel Booking',
        'description' => 'Pelajari cara membuat aplikasi pemesanan hotel yang interaktif menggunakan CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'hotel booking', 'url' => '/tags/hotel-booking/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'CodeIgniter: Membangun Aplikasi E-Commerce',
        'description' => 'Pelajari cara membuat platform e-commerce yang dinamis menggunakan framework CodeIgniter.',
        'image' => asset('assets/img/codigniter.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'codeigniter', 'url' => '/tags/codeigniter/'],
            ['name' => 'e-commerce', 'url' => '/tags/e-commerce/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
    [
        'title' => 'Laravel: Membangun Aplikasi Social Media',
        'description' => 'Pelajari cara membuat aplikasi media sosial interaktif menggunakan framework Laravel.',
        'image' => asset('assets/img/laravel.jpeg'),
        'publishedAt' => Carbon::now()->subWeek(rand(1, 52))->toIso8601String(),
        'linkedin' => 'https://www.linkedin.com/in/akhmad-safii-2019',
        'tags' => [
            ['name' => 'laravel', 'url' => '/tags/laravel/'],
            ['name' => 'social media', 'url' => '/tags/social-media/'],
            ['name' => 'web development', 'url' => '/tags/web-development/'],
        ],
    ],
];
